version: '3'
services:

  #https://github.com/wodby/mariadb
    mysql:
        image: mariadb:latest
        volumes:
            - "./database:/var/lib/mysql"
        restart: on-failure:5
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_NAME}

    phpfpm:
        depends_on:
            - mysql
        volumes:
            - ".:/var/www/html:delegated"
            - "./docker/config/php-fpm/php.ini:/usr/local/etc/php/php.ini:delegated"
            - "./docker/config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated"
        restart: on-failure:5
        build: ./docker/dockerfiles/php-fpm

    nginx:
        depends_on:
            - phpfpm
        ports:
            - "11000:80"
        image: nginx:latest
        volumes:
            - ".:/var/www/html:delegated"
            - "./logs/nginx:/var/log/nginx:delegated"
            - "./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated"
        restart: on-failure:5

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        ports:
            - 100:80
        restart: on-failure:5
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql

    mailcatcher:
        image: schickling/mailcatcher
        restart: on-failure:5
        ports:
            - "1135:1025"
            - "1190:1080"
        environment:
            MAILCATCHER_PORT: 1135
